#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#


apiVersion: v1
kind: ConfigMap
metadata:
    name: bookie-config
data:
    PULSAR_MEM: "\"-Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintHeapAtGC -verbosegc -XX:G1LogLevel=finest -XX:MaxGCPauseMillis=10 -Xms6g -Xmx6g -XX:MaxDirectMemorySize=8g\""
#    PULSAR_MEM: "\"-Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintHeapAtGC -verbosegc -XX:G1LogLevel=finest -XX:MaxGCPauseMillis=10 -Xms12g -Xmx12g -XX:MaxDirectMemorySize=12g\""
    dbStorage_writeCacheMaxSizeMb: "2048" # Write cache size (direct memory)
    dbStorage_readAheadCacheMaxSizeMb: "2048" # Read cache size (direct memory)
    dbStorage_rocksDB_blockCacheSize: "2147483648"
#    PULSAR_MEM: "\"-Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintHeapAtGC -verbosegc -XX:G1LogLevel=finest -XX:MaxGCPauseMillis=10 -Xms28g -Xmx28g -XX:MaxDirectMemorySize=28g\""
#    dbStorage_writeCacheMaxSizeMb: "4096" # Write cache size (direct memory)
#    dbStorage_readAheadCacheMaxSizeMb: "4096" # Read cache size (direct memory)
#    dbStorage_rocksDB_blockCacheSize: "4294967296"
    journalMaxSizeMB: "2048"
    zkServers: zk-0.zookeeper,zk-1.zookeeper,zk-2.zookeeper
#    statsProviderClass: org.apache.bookkeeper.stats.PrometheusMetricsProvider
    statsProviderClass: org.apache.bookkeeper.stats.NullStatsProvider
#    statsProviderClass: org.apache.bookkeeper.stats.CachingStatsProvider
    journalDirectory: /pulsar/journal
    ledgerDirectories: /pulsar/ledger
    journalMaxGroupWaitMSec: "1"
    numReadWorkerThreads: "16"
---

## BookKeeper servers need to access the local disks and the pods
## cannot be moved across different nodes.
## For this reason, we run BK as a daemon set, one for each node in the
## cluster, unless restricted by label selectors
apiVersion: extensions/v1beta1
kind: DaemonSet
#kind: Deployment
metadata:
    name: bookie
    labels:
        app: pulsar
        component: bookkeeper
        role: bookie
spec:
    template:
        metadata:
            labels:
                app: pulsar
                component: bookkeeper
                # Specify cluster to allow aggregation by cluster in
                # the metrics
                cluster: us-east
                role: bookie
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8000"

        spec:
            # Make sure multiple pods of ZK don't get scheduled on the
            # same node, unless there are no other available nodes
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: 1
                        podAffinityTerm:
                            labelSelector:
                                matchExpressions:
                                  - key: "app"
                                    operator: In
                                    values:
                                      - bookie
                            topologyKey: "kubernetes.io/hostname"

            containers:
              - name: bookie
                image: saandrews/pulsar:latest
                #image: apachepulsar/pulsar:1.20.0-incubating
                #image: apachepulsar/pulsar:1.22.0-incubating
                command: ["sh", "-c"]
                args:
                  - >
                    bin/apply-config-from-env.py conf/bookkeeper.conf &&
                    bin/apply-config-from-env.py conf/pulsar_env.sh &&
                    rm -rf /pulsar/ledger/current && rm -rf /pulsar/journal/current &&
                    bin/pulsar bookie
                ports:
                  - containerPort: 3181
                    name: client
                envFrom:
                  - configMapRef:
                        name: bookie-config
                env:
                  - name: advertisedAddress
                    valueFrom:
                        fieldRef:
                            fieldPath: status.podIP

                volumeMounts:
                  - name: journal-disk
                    mountPath: /pulsar/journal
                  - name: ledger-disk
                    mountPath: /pulsar/ledger

                # bin/bookkeeper shell bookiesanity

            initContainers:
                # The first time, initialize BK metadata in zookeeper
                 # Otherwise ignore error if it's already there
              - name: bookie-metaformat
                image: saandrews/pulsar:latest
                #image: apachepulsar/pulsar:1.20.0-incubating
                #image: apachepulsar/pulsar:1.22.0-incubating
                command: ["sh", "-c"]
                args:
                  - >
                    bin/apply-config-from-env.py conf/bookkeeper.conf &&
                    bin/bookkeeper shell metaformat --nonInteractive || true;
                envFrom:
                  - configMapRef:
                        name: bookie-config

            volumes:
                # Mount local disks
              - name: journal-disk
                persistentVolumeClaim:
                  claimName: journal-disk-claim
              - name: ledger-disk
                persistentVolumeClaim:
                  claimName: ledger-disk-claim
            nodeSelector:
              beta.kubernetes.io/instance-type: m4.4xlarge

---

##
## Define the Bookie headless service
## In practice, in this case, it is only useful to have a view of
## all the bookie pods that are present
##
apiVersion: v1
kind: Service
metadata:
    name: bookkeeper
    labels:
        app: pulsar
        component: bookkeeper
        role: bookie
spec:
    ports:
      - port: 3181
        name: server
    clusterIP: None
    selector:
        app: pulsar
        component: bookkeeper

---
##
## Run BookKeeper auto-recovery from a different set of containers
## Auto-Recovery makes sure to restore the replication factor when any bookie
## crashes and it's not recovering on its own.
##
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: bookie-autorecovery
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: pulsar
                component: bookkeeper-replication
                role: bookie
        spec:
            containers:
              - name: replication-worker
                image: saandrews/pulsar:latest
                #image: apachepulsar/pulsar:1.20.0-incubating
                #image: apachepulsar/pulsar:1.22.0-incubating
                command: ["sh", "-c"]
                args:
                  - >
                    bin/apply-config-from-env.py conf/bookkeeper.conf &&
                    bin/bookkeeper autorecovery
                envFrom:
                  - configMapRef:
                        name: bookie-config
                env:
                    ## Configure for lower mem usage
                  - name: PULSAR_MEM
                    value: "\" -Xmx256m \""
                  - name: PULSAR_GC
                    value: "\"  \""
            nodeSelector:
              beta.kubernetes.io/instance-type: m4.4xlarge


---
apiVersion: v1
kind: ConfigMap
metadata:
    name: bookie-config2
data:
    PULSAR_MEM: "\"-Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintHeapAtGC -verbosegc -XX:G1LogLevel=finest -XX:MaxGCPauseMillis=10 -Xms6g -Xmx6g -XX:MaxDirectMemorySize=8g\""
#    PULSAR_MEM: "\"-Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintHeapAtGC -verbosegc -XX:G1LogLevel=finest -XX:MaxGCPauseMillis=10 -Xms12g -Xmx12g -XX:MaxDirectMemorySize=12g\""
    dbStorage_writeCacheMaxSizeMb: "2048" # Write cache size (direct memory)
    dbStorage_readAheadCacheMaxSizeMb: "2048" # Read cache size (direct memory)
    dbStorage_rocksDB_blockCacheSize: "2147483648"
#    PULSAR_MEM: "\"-Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintHeapAtGC -verbosegc -XX:G1LogLevel=finest -XX:MaxGCPauseMillis=10 -Xms28g -Xmx28g -XX:MaxDirectMemorySize=28g\""
#    dbStorage_writeCacheMaxSizeMb: "4096" # Write cache size (direct memory)
#    dbStorage_readAheadCacheMaxSizeMb: "4096" # Read cache size (direct memory)
#    dbStorage_rocksDB_blockCacheSize: "4294967296"
    journalMaxSizeMB: "2048"
    zkServers: zk-0.zookeeper,zk-1.zookeeper,zk-2.zookeeper
#    statsProviderClass: org.apache.bookkeeper.stats.PrometheusMetricsProvider
    statsProviderClass: org.apache.bookkeeper.stats.NullStatsProvider
#    statsProviderClass: org.apache.bookkeeper.stats.CachingStatsProvider
    journalDirectory: /pulsar/journal1
    ledgerDirectories: /pulsar/ledger1
    journalMaxGroupWaitMSec: "1"
    numReadWorkerThreads: "16"
---

## BookKeeper servers need to access the local disks and the pods
## cannot be moved across different nodes.
## For this reason, we run BK as a daemon set, one for each node in the
## cluster, unless restricted by label selectors
apiVersion: extensions/v1beta1
#kind: DaemonSet
#kind: StatefulSet
kind: DaemonSet
#kind: Deployment
metadata:
    name: bookie2
    labels:
        app: pulsar
        component: bookkeeper
        role: bookie
spec:
    template:
        metadata:
            labels:
                app: pulsar
                component: bookkeeper
                # Specify cluster to allow aggregation by cluster in
                # the metrics
                cluster: us-east
                role: bookie
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8000"

        spec:
            # Make sure multiple pods of ZK don't get scheduled on the
            # same node, unless there are no other available nodes
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: 1
                        podAffinityTerm:
                            labelSelector:
                                matchExpressions:
                                  - key: "app"
                                    operator: In
                                    values:
                                      - bookie
                            topologyKey: "kubernetes.io/hostname"

            containers:
              - name: bookie
                image: saandrews/pulsar:latest
                #image: apachepulsar/pulsar:1.20.0-incubating
                #image: apachepulsar/pulsar:1.22.0-incubating
                command: ["sh", "-c"]
                args:
                  - >
                    bin/apply-config-from-env.py conf/bookkeeper.conf &&
                    bin/apply-config-from-env.py conf/pulsar_env.sh &&
                    rm -rf /pulsar/ledger1/current && rm -rf /pulsar/journal1/current &&
                    bin/pulsar bookie
                ports:
                  - containerPort: 3181
                    name: client
                envFrom:
                  - configMapRef:
                        name: bookie-config2
                env:
                  - name: advertisedAddress
                    valueFrom:
                        fieldRef:
                            fieldPath: status.podIP

                volumeMounts:
                  - name: journal-disk
                    mountPath: /pulsar/journal1
                  - name: ledger-disk
                    mountPath: /pulsar/ledger1

                # bin/bookkeeper shell bookiesanity

            initContainers:
                # The first time, initialize BK metadata in zookeeper
                 # Otherwise ignore error if it's already there
              - name: bookie-metaformat
                image: saandrews/pulsar:latest
                #image: apachepulsar/pulsar:1.20.0-incubating
                #image: apachepulsar/pulsar:1.22.0-incubating
                command: ["sh", "-c"]
                args:
                  - >
                    bin/apply-config-from-env.py conf/bookkeeper.conf &&
                    bin/bookkeeper shell metaformat --nonInteractive || true;
                envFrom:
                  - configMapRef:
                        name: bookie-config2

            volumes:
                # Mount local disks
              - name: journal-disk
                persistentVolumeClaim:
                  claimName: journal-disk-claim2
              - name: ledger-disk
                persistentVolumeClaim:
                  claimName: ledger-disk-claim2
            nodeSelector:
              beta.kubernetes.io/instance-type: m4.4xlarge

---

##
## Define the Bookie headless service
## In practice, in this case, it is only useful to have a view of
## all the bookie pods that are present
##
apiVersion: v1
kind: Service
metadata:
    name: bookkeeper2
    labels:
        app: pulsar
        component: bookkeeper
        role: bookie
spec:
    ports:
      - port: 3181
        name: server
    clusterIP: None
    selector:
        app: pulsar
        component: bookkeeper

---
##
## Run BookKeeper auto-recovery from a different set of containers
## Auto-Recovery makes sure to restore the replication factor when any bookie
## crashes and it's not recovering on its own.
##
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: bookie-autorecovery2
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: pulsar
                component: bookkeeper-replication
                role: bookie
        spec:
            containers:
              - name: replication-worker
                image: saandrews/pulsar:latest
                #image: apachepulsar/pulsar:1.20.0-incubating
                #image: apachepulsar/pulsar:1.22.0-incubating
                command: ["sh", "-c"]
                args:
                  - >
                    bin/apply-config-from-env.py conf/bookkeeper.conf &&
                    bin/bookkeeper autorecovery
                envFrom:
                  - configMapRef:
                        name: bookie-config2
                env:
                    ## Configure for lower mem usage
                  - name: PULSAR_MEM
                    value: "\" -Xmx256m \""
                  - name: PULSAR_GC
                    value: "\"  \""
            nodeSelector:
              beta.kubernetes.io/instance-type: m4.4xlarge
